name: Raecipes
version: 1.0.0
author: Segers Pieterjan
main: com.gmail.segers1.pieterjan.raecipes.Raecipes
api-version: 1.12.2

commands:
  firstname:
     description: Set the firstname of your character.
     usage: /firstname <name>
     aliases:
       - fn
       - first
  lastname:
     description: Set the lastname of your character.
     usage: /lastname <name>
     aliases:
       - ln
       - last
  resetname:
    description: Resets the name of your character to your IGN.
    usage: /resetname
    aliases:
      - rn
  colors:
    description: A handy tooltip of all the colours!
    usage: /colors
    aliases:
      - colours
  raecipes:
    description: All admin commands.
    usage: /raecipes
    aliases:
      - rae
