name: Raecipes
version: 1.0.0
author: Segers Pieterjan
main: com.gmail.segers1.pieterjan.raecipes.Raecipes
api-version: 1.12.2

commands:
  firstname:
     description: Set the firstname of your character.
     usage: /firstname <name>
     aliases:
       - fn
       - first
#     permission: raecipes.firstname
  lastname:
     description: Set the lastname of your character.
     usage: /lastname <name>
     aliases:
       - ln
       - last
#     permission: raecipes.lastname
  resetname:
    description: Resets the name of your character to your IGN.
    usage: /resetname
    aliases:
      - rn
  #     permission: raecipes.resetname
  colors:
    description: A handy tooltip of all the colours!
    usage: /colors
    aliases:
      - colours
#     permission: raecipes.colors
  raecipes:
    description: All admin commands.
    usage: /raecipes
    aliases:
      - rae
#     permission: raecipes.raecipes

permissions:
  raecipes.*:
    description: Allows use of all commands.
    default: false
    children:
      raecipes.all: true
  raecipes.all:
    description: Allows use of all commands.
    default: false
    children:
      raecipes.firstname: true
      raecipes.lastname: true
      raecipes.colors: true
      raecipes.resetname: true
      raecipes.raecipes: true
  raecipes.member:
    description: A collection of basic commands.
    default: false
    children:
      raecipes.firstname: true
      raecipes.lastname: true
      raecipes.colors: true
      raecipes.resetname: true
  raecipes.firstname:
    description: Allows use of the `/firstname` command.
    default: false
  raecipes.lastname:
    description: Allows use of the `/lastname` command.
    default: false
  raecipes.colors:
    description: Allows use of the `/color` command.
    default: false
  raecipes.resetname:
    description: Allows use of the `/resetname` command.
    default: false
